### ISSUE TITLE
[ST-5-1-1] Research and Select a Golang Library to Use

### ISSUE THREAD

**Issue by BrodyGimson** [SENG499-S22-Company3/algorithm-1#96]
- [ ] Research and play around with different libraries to find one that will help find a solution for our problem
- [ ] Select a library that will work best for us or determine that algorithm is not feasible

**Comment by nathantutak** [comment]
The best candidates I found were:
1. https://github.com/tomcraven/goga
2. https://github.com/soypat/mu8
3. https://github.com/MaxHalford/gago

I think we should use 1. The biggest reason is that this one is the most popular of the 3, meaning theres more working examples we can look at in other projects to base our solution off of. This library has good documentation and examples, and it's pretty simple and straightforward. Another advantage is that the way this library represents genes is very concrete, the other libraries are very open ended and flexible for representing genes but that will make them harder to use.

The second option seems good but has higher complexity and feels less organized. The third library is no longer supported, we would want to move to the newer version of the project which is much broader in scope and has way more than what we need.

**Comment by nathantutak** [comment]
Some other general notes from my research:

To use goga the main things we will need are
1. model the problem using bitsets 
2. make a heuristic function to evaluate genes based on the hard and soft constraints

goga also has support for running simulations concurrently.

returning multiple schedules
goga can also be used to get the n best schedules. However, since we want to generate 3 or so schedules that are somewhat different, taking the n best wont actually be helpful since they’ll probably be very similar. I think doing some kind of random seed to get different results as discussed before will work for this.

I think the fact that eaopt is implementing various different evolutionary algorithms will make it harder to understand what the library is doing (and how to use it for our specific purpose). I do think eaopt has a lot of features that could be helpful (setting time limits and different evolution strategies).

The fact that eaopt is more open ended with how the genes are modelled and how mutation happens might make things more difficult since its up to us to make the right design. With goga its much more restrictive, but I think this can help us since as long as we can model the problem as a bitset then the algorithm will definitely work

**Comment by marksigilai** [comment]
Some more notes on eaopt

- for eaopt, manipulation can be done directly on the structs/maps that we currently have which should be simple
- essentially, we have to write 4 functions Evaluate, Mutate, Clone, Crossover of which Mutate and Crossover will require some thought & effort
- eaopt has the option of not using a Crossover which would make it easy, but not sure if this will result in a sub optimal solution
- eaopt allows flexibility in choosing models - how to evolve the schedules (https://github.com/MaxHalford/eaopt#models) - should really affect performance of the alg. Pretty easy to switch between models as well and v helpful

**Comment by BrodyGimson** [comment]
Need to decide which library to use, or we could split into teams and try both libraries to see which seems more feasible. Need to discuss as a group.

**Comment by BrodyGimson** [comment]
Found that both libraries would work for this task. Both teams are going to work on implementing a production version of each and then weigh both to choose one.
